### ISSUE TITLE
Error Retrieving Mesa When Trying To Install VICE on RPI

### ISSUE THREAD

**Issue by paulhocker** [idun-project/idun-vice#1]
When using pacman is asked which mesa driver to install. I selected option 1 which waslibglvnd.

I must admit do not have much exp with Arch. That said, receiving an error saying that it cannot locate the Mesa package

mesa-23.0.1-2 from mirror.al.org

looking on that mirror, it only has the latest which is 23.0.2-2 -- so this results in a 404 and the install fails.

http://nj.us.mirror.archlinuxarm.org/armv7h/extra/

I am trying to install the package directly (no luck yet) but I fear that some of the other dependencies might be broke too.

I am not sure how to resolve this.

**Comment by paulhocker** [comment]
I found a video on how to refresh the package list.

Seems to be installing now.

:)

**Comment by paulhocker** [comment]
Got it working.

![IMG_2134](https://user-images.githubusercontent.com/2214652/232174744-c3c0376a-ea63-4ed5-89d6-a2ae196219f1.PNG)

Perhaps you can add something to the readme to let people know that they need to update the pacman packages before trying to run it.

You can close this issue.

**Comment by idun-project** [comment]
Cool. I updated the README with link to helpful pacman documentation.
